FROM python:3.7-slim
RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential \
  cmake \
  git \
  curl \
  vim \
  ca-certificates \
  libjpeg-dev \
  libpng-dev \
  software-properties-common swig mecab libmecab-dev mecab-ipadic-utf8 &&\
  rm -rf /var/lib/apt/lists/*
RUN mkdir /app
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
